name: Repository Dispatch

on:
  push:
    branches:
    - master

jobs:
  trigger-action:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: winwangqi/notebook_website
        event-type: trigger-action-by-content
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
